task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1 # ship
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/Dataset/ship_dataset_v0
    ann_file: /root/autodl-tmp/Dataset/ship_dataset_v0/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 20
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/autodl-tmp/Dataset/ship_dataset_v0
    ann_file: /root/autodl-tmp/Dataset/ship_dataset_v0/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 20
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
